crev-dev/cargo-crev

src/main.rs
src/opts.rs
src/repo/mod.rs
src/repo/staging.rs

add rm subcommand

---

cargo-crev/README.md
cargo-crev/src/main.rs
cargo-crev/src/opts.rs
crev-bin/src/main.rs
crev-bin/src/opts.rs
crev-lib/src/local.rs

Fix #49: crev id gen changed to crev id new

---

Cargo.lock
recursive-digest/Cargo.toml
recursive-digest/src/lib.rs
recursive-digest/tests/sanity.rs

Improve error handling using `failure` and general refactor.

Refactor recursive-digest

---

cargo-crev/src/main.rs

@dpc What do you think about something as simple as this for now?

Main function acts as root error handler

---

cargo-crev/src/main.rs
crev-bin/src/main.rs
crev-lib/src/id.rs
crev-lib/src/local.rs
crev-lib/src/repo/mod.rs
crev-lib/src/tests.rs

Changing lib API interface as progress towards completing issue #8 .

Lib API obtains passphrase using argument closure

---

crev-lib/src/id.rs

I thought a finite loop would be reasonable encase a non-IO but incorrect `passphrase_callback` is provided.

#8: Better error messages when locked id password is wrong; given incorrect password, loops five times

---

README.md

encurage -> encourage

---

.gitignore

Would make me, and perhaps others, happy:)
Checklist:

Ignoring Intellij files to get a clean directory

---

cargo-crev/src/opts.rs

This is my solution for future new users asking this question: https://github.com/dpc/crev/issues/39#issuecomment-451898824
If you'd rather have this somewhere else, feel free to let me know. When I tried putting it in long_about it messed up the formatting of the rest of the help somehow, but I think this is the appropriate place in any case.
Checklist:

Documenting contents of `verify deps`

---

crev-lib/src/local.rs

Remove `qualifiers`, only affects MacOS.

---

cargo-crev/CHANGELOG.md

Just some corrections and removed trailing `/`.

Improve CHANGELOG

---

.travis.yml

Use `rustfmt` only in `stable`, since there are minor differences

---

cargo-crev/src/main.rs

I just tried to run `cargo clippy`:)
Checklist:

Remove clone

---

cargo-crev/src/doc/getting_started.md

Spelling fixes, minor command fixes, and a few small grammar changes.
Checklist:

Minor updates to getting started doc

---

cargo-crev/src/dep/mod.rs
cargo-crev/src/main.rs

I'm not 100% sure I understood the semantic of VerificationFailed so please check it looks OK.

restore returning a non-zero code when not all crates are verified

---

Cargo.lock
cargo-crev/src/doc/getting_started.md
crev-lib/Cargo.toml
crev-lib/src/id.rs

To drop the dependency on clang/LLVM stuff

Replace argonautica with rust-argon2

---

crev-lib/src/util/mod.rs

Tested with:
```
C:\>git config --global core.editor "\"%LOCALAPPDATA%\Programs\Microsoft VS Code\Code.exe\" --wait"
C:\>type "%USERPROFILE%\.gitconfig" | findstr editor
editor = \"C:\\Users\\MaulingMonkey\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe\" --wait
```
Which works for both git commits and cargo crev editing.
Checklist:

Fix windows support for editors with arguments, quotes.

---

crev-data/src/proof/review/package.rs

I've taken to using:
```yaml
...
comment: |
Long description
over multiple lines
describing my review process
and resulting concerns/rationale.
```
Using write_as_headerless_yaml turns this into a soup of quoted \ns, which while valid/correct, isn't very readable.  This changes the Display traits a bit to fix that.  On the other hand, maybe it'd be less confusing to keep the quoted style by default / for single line comments...?

Pretty print Package[Draft] comments.

---

cargo-crev/src/shared.rs

On Windows, diff is likely available through a git install, but *not* in
%PATH%.  Specifically, the git installer warns that adding *nix tools to
%PATH% will change the behavior of some built in windows commands like
"find", and by default doesn't do this to avoid breaking anything.

run_diff: Support non-%PATH% diff from windows git

---

cargo-crev/src/main.rs
cargo-crev/src/opts.rs

I didn't change `fetch`, because I don't know what are the implications of fetching an URL without trusting it.
Fixes #220

Combine push/pull into publish/update

---

cargo-crev/src/doc/getting_started.md

Fix getting started command: remove query subcommand.

---

cargo-crev/src/deps.rs
cargo-crev/src/verify_deps.rs

fixes #265
Checklist:
That would have modified a bunch of unrelated files
N/A

Fix invalid command suggestion

---

ci/travis-musl-openssl.sh

OpenSSL project has deleted 1.0 tarballs

OpenSSL 1.0.x is dead

---

cargo-crev/src/deps.rs
cargo-crev/src/main.rs
crev-data/src/id.rs
crev-data/src/proof/trust.rs
crev-lib/src/id.rs
crev-lib/src/local.rs
crev-lib/src/proofdb.rs

This is a prerequisite for #300

Optional URL field

---

crev-lib/src/local.rs

If there's no self-reported URL known, then fetch the URL to find the self-report there. If the URL doesn't contain the identity, then create a trust proof without a URL. This way wrong URLs won't spread through proofs.

Don't create trust proofs for bogus URLs

---

cargo-crev/src/main.rs
cargo-crev/src/opts.rs
crev-bin/src/opts.rs
crev-lib/src/local.rs
crev-lib/src/proofdb.rs

`cargo crev trust`

---

cargo-crev/src/doc/mod.rs

Fix typos in documentation

---

.travis.yml
cargo-crev/src/main.rs
cargo-crev/src/repo.rs
crev-lib/src/local.rs
crev-lib/src/proofdb.rs
crev-lib/src/tests.rs

Add CI format check.

---

cargo-crev/src/repo.rs
cargo-crev/src/review.rs
crev-common/src/lib.rs
crev-common/src/serde.rs
crev-data/src/proof/mod.rs
crev-data/src/proof/review/code.rs
crev-data/src/proof/review/package.rs
crev-data/src/proof/trust.rs
crev-data/src/tests.rs
crev-lib/src/id.rs
crev-lib/src/lib.rs
crev-lib/src/local.rs
crev-lib/src/repo/mod.rs
crev-lib/src/repo/staging.rs
crev-lib/src/tests.rs
crev-lib/src/tests/issues.rs
crev-lib/src/util/mod.rs
crev-wot/src/lib.rs

Apply clippy lint.

---

cargo-crev/src/main.rs
crev-lib/src/local.rs

CLI argument checking has been relocated from crev-lib to cargo-crev. Removed method Local.generate_id_interactive, custom interactive password callback implemented in cargo-crev.

Move all stdout and stderr from Local.generate_id to cargo-crev.

---

Cargo.lock
crev-data/Cargo.toml
crev-data/src/id.rs
crev-data/src/level.rs
crev-data/src/lib.rs
crev-data/src/proof/content.rs
crev-data/src/proof/mod.rs
crev-data/src/proof/review/code.rs
crev-data/src/proof/review/package.rs
crev-data/src/proof/trust.rs
crev-data/src/tests.rs
crev-lib/src/local.rs
crev-wot/Cargo.toml
crev-wot/src/lib.rs

Un-failure part 1

---

crev-lib/src/id.rs
crev-lib/src/util/mod.rs

Rename field for clarity: pass --> passphrase_config

---

cargo-crev/src/edit.rs
cargo-crev/src/shared.rs
crev-lib/src/local.rs
crev-lib/src/proof.rs

Refactor symbol names.

---

crev-lib/rc/doc/editing-code-review.md
crev-lib/rc/doc/editing-package-review.md
crev-lib/rc/doc/editing-trust.md

Fix a few spelling errors in doc files

---

cargo-crev/src/deps.rs
cargo-crev/src/deps/print_term.rs
cargo-crev/src/deps/scan.rs
cargo-crev/src/info.rs
cargo-crev/src/main.rs
cargo-crev/src/opts.rs
cargo-crev/src/repo.rs
cargo-crev/src/shared.rs
crev-common/src/lib.rs
crev-data/src/id.rs
crev-lib/src/id.rs
crev-lib/src/lib.rs
crev-lib/src/local.rs
crev-lib/src/proof.rs
crev-lib/src/tests.rs
crev-lib/src/tests/issues.rs
crev-lib/src/util/mod.rs
crev-wot/src/lib.rs

I noticed that the PR template asks contributors to format the code,
but the repository itself is not formatted. This PR should fix that.
Checklist:

Run everything through `cargo fmt --all`

---

cargo-crev/src/edit.rs
cargo-crev/src/main.rs
cargo-crev/src/review.rs
crev-lib/rc/doc/editing-trust.md

Warn users about misusing distrust proofs.

---

cargo-crev/README.md

Fix crates.io badge

---

cargo-crev/src/doc/mod.rs

Do two minor grammar improvements.
Checklist:

Improve grammar
