crev-bin/src/opts.rs

Command line sub-commands were not listed alphabetically because the default `varify` command name started with a capital letter.

Add structopt name tag to varify command line option

---

recursive-digest/src/lib.rs
recursive-digest/tests/sanity.rs

This is the start of removing platform-dependent API (#81). I have used `to_str` instead of `to_str_lossy` and propagated the errors upwards. The code could be simpler when using the latter, but it's better to err on the safe side.

Use to_str instead of as_bytes

---

crev-lib/src/local.rs

Creating the proof directory before cloning fixes `cargo crev new id` on my computer (Windows).

Create proofs directory

---

.travis.yml

closes #177 
I added clippy.
Off-Topic: I noticed travis has no caches so it takes time to complete. Should we set cache?
Checklist:

Use clippy on travis

---

.travis.yml
README.md
cargo-crev/src/main.rs
recursive-digest/tests/sanity.rs

Makes a Travis build actually fail if rustfmt or clippy aren't happy, and fixes two clippy lints and a few typos.
Checklist:

Enforce clippy on Travis

---

cargo-crev/src/doc/getting_started.md

I found it confusing that `dpc` was used in the doc to refer to https://github.com/dpc/crev-proofs specifically, while also having the -test repository under dpc also.

Use a placeholder name for the example user in getting started

---

cargo-crev/CHANGELOG.md
cargo-crev/src/opts.rs

Seems that the help text has to be attached within the subcommand enum
to show up

Fix cargo crev verify's after_help not showing

---

cargo-crev/src/dep/computer.rs
cargo-crev/src/tui/mod.rs
cargo-crev/src/tui/table_view.rs
cargo-crev/src/tui/user_events.rs
cargo-crev/src/tui/verify_screen.rs

* crates are alphabetically sorted
* numbers of owners and issues are easier to read
* better column widths
* no resize computations when screen didn't change size
* screen is cleared on real resize to avoid artefacts
* mouse wheel scroll

A few cosmetic improvements of the Verify Tui

---

appveyor.yml
recursive-digest/tests/sanity.rs

Tests fail if a user is not able to create symlinks, which is true most
of the time on Windows.

Ignore symlink test on windows

---

crev-common/src/lib.rs
crev-lib/src/local.rs

I'm not sure if this counts as a breaking change (should I try to keep the original path on !windows?), or if this is even the right place to make this change, or if there's other places that also need fixing, but this at least fixes basic commands like `cargo crev open ...` on windows when source == PROJECT_SOURCE_CRATES_IO == `https:\\crates.io`.  Turns out windows doesn't like `:` in filenames.  If you prefer an alternatives, just let me know.
Checklist:

Don't use ':' in filenames, windows doesn't like them.

---

cargo-crev/CHANGELOG.md
cargo-crev/src/doc/getting_started.md
cargo-crev/src/main.rs
cargo-crev/src/opts.rs
cargo-crev/src/review.rs
crev-data/src/proof/review/package.rs
crev-lib/src/local.rs

```diff 
SUBCOMMANDS:
-    advise      Create advisory urging to upgrade to given package version
clean       Clean a crate source code (eg. after review)
diff        Diff between two versions of a package
distrust    Distrust an Id
edit        Edit README.md of the current Id, ...
-    export      Export an id, ...
fetch       Fetch proofs from external sources
-    flag        Flag a crate as buggy/low-quality/dangerous
git         Run raw git commands in the local proof repository
goto        Start a shell in source directory of a crate under review
help        Prints this message or the help of the given subcommand(s)
-    new         Create an Id, ...
+    id          Manage your own Id (create new, show, export, import, switch)
import      Import proofs, ...
open        Open source …
```

Fewer subcommands

---

cargo-crev/README.md

I think that the README title is currently too complicated. It's trying to explain too much. It contains a hyperlink, brackets, and a forward slash. It also wraps around on my screen.
I think that it should be very simple and easy to consume because it's the first thing that a new visitor will see.
Checklist:

Simplify README title and introduction. Added the Features heading.

---

crev-data/src/proof/mod.rs

Quick workaround for crev-dev/cargo-crev#246
Checklist:
* CHANGELONG.md is currently a placeholder...?

Double proof body limit from 16k to 32k

---

cargo-crev/src/doc/getting_started.md

This appears to be the right command, 'query' is not a top-level subcommand.
Edit: found a few more

DOC: Fix commands that moved under 'cargo crev repo'

---

cargo-crev/src/opts.rs

Looks like a bad copy&paste:
```
$ cargo crev id
cargo-crev-id 0.10.1
[...]
SUBCOMMANDS:
current     Show your current Id
distrust    Distrust an Id
[...]
query       Distrust an Id
```

Fix help message for 'id query'

---

Cargo.lock
cargo-crev/CHANGELOG.md
cargo-crev/src/dyn_proof.rs
cargo-crev/src/info.rs
crev-common/src/lib.rs
crev-data/Cargo.toml
crev-data/src/id.rs
crev-data/src/proof/mod.rs
crev-data/src/proof/review/code.rs
crev-data/src/proof/review/package.rs
crev-data/src/proof/trust.rs
crev-lib/src/proofdb.rs

This allows users to use `cargo install cargo-crev` (without `--locked`).
Checklist:

Pin ed25519-dalek

---

cargo-crev/CHANGELOG.md
cargo-crev/src/deps/scan.rs

Fixes #272 
... though I should note that while this fixes the hang, the output is still weird (Windows):
```cmd
D:\repos\cad97\pointer-utils>cargo crev crate verify
status reviews     downloads    owner  issues lines  geiger flgs crate                version         latest_t
local   0  0        ?         ?
0/0    0/0     355      49      erasable             1.0.0-dev*
local   0  0        ?         ?
0/0    0/0     247       0      rc-borrow            1.0.0-dev*
```

fix: if owners fetch fails, treat as empty list

---

cargo-crev/src/deps.rs
cargo-crev/src/deps/print_term.rs
cargo-crev/src/deps/scan.rs
cargo-crev/src/tui/verify_screen.rs

New output:
```
D:\repos\cad97\this-is-not-published>cargo crev crate verify
status reviews     downloads    owner  issues lines  geiger flgs crate                version         latest_t
local   0  0        ?         ?  ?/?    0/0       3       0      this-is-not-published 0.1.0*
```
This also incidentally fixes the `println!` causing the broken line seen in #273.

Handle no known crates-io owners specifically

---

cargo-crev/src/main.rs
crev-lib/src/local.rs
crev-lib/src/proofdb.rs

This does not alter functionality in any way. It's just a rename.

Rename URL lookup fields and methods

---

cargo-crev/src/main.rs
cargo-crev/src/shared.rs
crev-data/src/id.rs
crev-lib/src/id.rs
crev-lib/src/local.rs
crev-lib/src/proofdb.rs

Currently it's possible to "trust" anything that base64-decodes, even if it doesn't have the correct length.

Verify syntax of Ids

---

cargo-crev/src/main.rs
crev-lib/src/local.rs
crev-lib/src/proofdb.rs
crev-lib/src/tests.rs
crev-lib/src/tests/issues.rs

#298
I think it'd be nice to save verified Id<=>Url mappings somewhere to disk, outside of the cache. Maybe even keep track of all fetched URLs as part of config, because it's weird that `crev repo fetch all` does nothing after a cache clear.
I'm using network for verification. Perhaps WoT could also be used, i.e. if a trust proof of person A I already trust contains a URL of person B, then consider that a valid URL for the person B even if it hasn't been fetched.

Tracking which URL<>Id mappings have been verified

---

cargo-crev/src/deps.rs
cargo-crev/src/dyn_proof.rs
cargo-crev/src/main.rs
cargo-crev/src/opts.rs
cargo-crev/src/repo.rs
cargo-crev/src/review.rs
cargo-crev/src/shared.rs
crev-bin/src/opts.rs
crev-data/src/id.rs
crev-data/src/lib.rs
crev-data/src/proof/content.rs
crev-data/src/proof/review/code.rs
crev-data/src/proof/review/package.rs
crev-data/src/proof/trust.rs
crev-data/src/tests.rs
crev-lib/src/id.rs
crev-lib/src/local.rs
crev-lib/src/tests.rs
crev-lib/src/tests/issues.rs
crev-wot/src/lib.rs

Rename `OwnId` to `UnlockedId`.
Rename `PubId` to `PublicId`.
Rename function `Local.show_own_ids()` to `Local.show_current_user_public_ids()`.
Rename function `Local.list_ids()` to `Local.get_current_user_public_ids()`.

Clarify id structure names

---

cargo-crev/src/main.rs
crev-lib/src/local.rs

Move functionality for printing current ID from crev-lib to cargo-crev.

---

.pre-commit-config.yaml
HACKING.md
crev-lib/src/util/mod.rs

Runs `cargo fmt` before forming a commit. See https://pre-commit.com/ for usage.

Add config file for optional pre-commit hooks.

---

.pre-commit-config.yaml
cargo-crev/src/main.rs
cargo-crev/src/shared.rs
crev-lib/src/proof.rs

What do you think about this sort of thing? What's the point of proof storage without commit?
Proof creation code probably needs to be moved out of `cargo-crev`. I need this sort of thing for `py-crev-lib`.

Separate ID trust proof creation from storage.

---

cargo-crev/src/doc/getting_started.md

Just started to explore the opportunities crev offers to a Secure Development Lifecycle and crossed some minor issues in "Getting started".
Checklist:

Update and fix typos in getting_started.md

---

cargo-crev/src/doc/getting_started.md

Checklist:
Trivial fix.
Encountered while setting up Crev for myself.

Fix missing `git` subcommand in documentation

---

cargo-crev/README.md
cargo-crev/src/opts.rs

Checklist:
* [-] `cargo +nightly fmt --all`
* [-] Modify `CHANGELOG.md` if applicable
This is useful for when room IDs change (due to upgrades or else), and the readmes still point to a room ID instead of an alias.

Replace room ID with #crev

---

cargo-crev/src/doc/getting_started.md
cargo-crev/src/opts.rs

I wanted to review a diff and it took me a hot minute to figure out the correct incantation. These changes would've helped me get it done faster. Hopefully they'll help the next person then :)
I couldn't name the option argument "version" because that is already taken by something else — I couldn't figure out by what exactly, but if I use "version", Clap panics at run-time.
Checklist:

Improve docs for `crev review --diff`

---

cargo-crev/CHANGELOG.md
cargo-crev/src/main.rs

Original issue: `trust` without  `--level` option pops up an editor. Setting trust level to `low` and closing the editor caused crev to silently ignore the change and make a trust proof at default `medium`.
Checklist:

Fix interactive use of `trust` and `id trust` to actually read the proofs edited

---

cargo-crev/src/main.rs
cargo-crev/src/shared.rs

`deps::verify_deps` returns `CommandExitStatus::VerificationFailed` for `cargo crev verify` if at least one dependency is unverified, but the `?;` consumes the `Result<_>` and discards the inner `CommandExitStatus`:
https://github.com/crev-dev/cargo-crev/blob/f54289128ad8075ebffe47fd080fdac084f51c2e/cargo-crev/src/main.rs#L629-L631
causing a fall-through to:
https://github.com/crev-dev/cargo-crev/blob/f54289128ad8075ebffe47fd080fdac084f51c2e/cargo-crev/src/main.rs#L633-L635
Shoutout to [@c3h2_ctf](https://twitter.com/c3h2_ctf)

Exit the program with CommandExitStatus from deps::verify_deps

---

cargo-crev/src/shared.rs
crev-lib/src/local.rs
crev-lib/src/util/git.rs

Support the `http_proxy`, etc. environment variables and the git proxy
config.

Add HTTP Proxy Support

---

cargo-crev/CHANGELOG.md
cargo-crev/src/crates_io.rs
cargo-crev/src/deps/print_term.rs
cargo-crev/src/info.rs
cargo-crev/src/main.rs
cargo-crev/src/opts.rs
cargo-crev/src/shared.rs
cargo-crev/tests/clitest.rs
crev-common/src/blake2b256.rs
crev-lib/src/lib.rs
crev-lib/src/local.rs
crev-lib/src/util/mod.rs
crev-wot/src/lib.rs

I’ve included a bit extra, and another commit that applies rustfmt to the *rest* of the repository (not my stuff). Decide what you will of it all.
Seemed to work on my machine. Not especially conducive to adding a test case.
See the commit messages.
There wasn’t a consistent style in CHANGELOG.md for me to follow: wrap or not, present or past tense, full stop at end or not. I chose what I think is reasonable, and we can change it if you like.
Fixes #435.

Move proofs to the data directory

---

Cargo.lock
cargo-crev/CHANGELOG.md
cargo-crev/Cargo.toml

This PR bumps the Cargo dependency to `0.61.1` to fix #470 which was blocked by https://github.com/rust-lang/cargo/issues/10446
Checklist:

Bump Cargo dependency, fix #470

---

cargo-crev/src/opts.rs
crev-wot/src/lib.rs
crev-wot/src/tests.rs
crev-wot/src/trust_set.rs

to be able to walk those in the WoT. Their effect is normally disabled
by having their default be higher than the maximum depth/cost.
If e.g. one would like to know if there is any review out there for a
crate, I trust some proof repos with level none. With this change I can
then download every repo I can see:
crev repo fetch trusted --none-cost 4
Checklist:

Add arguments --none-cost N and --distrust-cost N

---

cargo-crev/CHANGELOG.md
cargo-crev/src/review.rs
cargo-crev/src/shared.rs

The checks were back to front, checking that the crate root wasn’t in the current directory, rather than that the current directory wasn’t in the crate root.
See the commit messages for more details.

Fix working directory checks for clean and review

---

cargo-crev/src/opts.rs

Small drive-by commit while chasing a different problem.
Checklist:

Fix cmdline help of "verify --dev-dependencies"

---

cargo-crev/CHANGELOG.md
cargo-crev/src/main.rs
cargo-crev/src/opts.rs
cargo-crev/src/review.rs
crev-data/src/proof/content.rs
crev-data/src/proof/mod.rs
crev-data/src/proof/review/code.rs
crev-data/src/proof/review/package.rs
crev-data/src/proof/trust.rs
crev-wot/src/lib.rs

PoC implementation for this discussion: https://github.com/crev-dev/cargo-crev/discussions/492
"How to deal with a person leaving an organization?"
This commands allows to find existing proofs
and sign them again with a different id.
This comes in handy when an id is going be revoked but
the trust of the existing reviews should be retained by a new id.
Scenarios:
- Old id got compromised
- Person leaves an organization, so organization can reissue
existing reviews using a different id to maintain trust level.
Checklist:
Code is originally based upon the "proof find" code.

Add new "proof reissue" command

---

cargo-crev/CHANGELOG.md
cargo-crev/src/opts.rs

This allows easily using only directly trusted Ids:
```
crev id query trusted --direct
```
Checklist:

Add `--direct` flag to trust params

---

flake.nix

Fixes https://github.com/crev-dev/cargo-crev/issues/515
Checklist:

Build on macOS+nix, without native libraries globally installed

---

cargo-crev/src/opts.rs
crev-data/src/proof/trust.rs

Explain possible trust level values in help and error messages. These help/error messages are shown with `cargo crev trust --help` and upon passing a unexpected parameter with `cargo crev trust --level foo`.
```
$ cargo crev trust --level --help
cargo-crev-trust 0.23.3
Add a Trust proof by an Id or a URL
USAGE:
cargo crev trust [FLAGS] [OPTIONS] [public-ids-or-urls]...
FLAGS:
-h, --help              Prints help information
--no-commit         Don't auto-commit local Proof Repository
--no-store          Don't store the proof
--overrides         Enable overrides suggestions
--print-signed      Print signed proof content on stdout
--print-unsigned    Print unsigned proof content on stdout
-V, --version           Prints version information
OPTIONS:
--level <level>    Shortcut for setting …
```

Explain possible trust level values in help and error messages.

---

cargo-crev/src/deps.rs

I noticed that `cargo crev verify --skip-known-owners` always returns an empty list, even when crates without any known owners are part of the dependencies.
This pull request contains three commits:
1. The fix for the concrete problem.
2. A patch to make `--skip-known-owners` more robust if no owner list is available: Instead of assuming that there _are_ known authors, it is now assumed that there are _no_ known authors.
3. A small local refactor to make the decision logic more obvious.
Feel free to pick what you actually want to merge :-)

Fix --skip-known-owners

---

crev-common/src/blake2b256.rs
crev-lib/src/local.rs

fix: "No such file or directory" on `trust` before first ids

---

cargo-crev/README.md
cargo-crev/src/doc/compiling.md
cargo-crev/src/doc/getting_started.md
cargo-crev/src/doc/mod.rs
crevette/README.md

The master branch was renamed on GitHub - links from documentation (etc.) needs to be updated to point to the main branch without GitHub 
putting up a warning banner.
(cargo format not done as no code change)
Checklist:

Repoint master branch links and mentions

---

flake.lock

This should update rust compiler.
Re https://github.com/crev-dev/cargo-crev/issues/675

chore: `nix flake lock --update-input fenix`

---

Cargo.lock
crevette/Cargo.toml

fix(deps): use index-guix dependency from crates.io

---

cargo-crev/src/deps.rs

Otherwise the new command prompt is appended to the end of the message and harder for users to see.
Checklist:

Write a newline after message about no trusted reviewers

---

cargo-crev/CHANGELOG.md
cargo-crev/Cargo.toml
cargo-crev/src/shared.rs

Because geiger now is beaks expected behavior with normal rust syntax,
and needed update is landing [so slowly there](https://github.com/geiger-rs/cargo-geiger/pull/518),
I'm pretty sure could be great to workaround it temporarily not fixed yet - make geiger optional.
This PR is "fixes" #735.
Checklist:
- - -
About checklist:
* `cargo +nightly fmt --all` a lot of modules are reformatted that are not related to the purpose of this PR. Maybe it's not worth it?

Make geiger optional dependency

---

.github/workflows/ci-nix.yml
Cargo.lock
cargo-crev/CHANGELOG.md
cargo-crev/Cargo.toml
cargo-crev/src/creds.rs
cargo-crev/src/main.rs
cargo-crev/src/term.rs

This PR adds mac keychain basic support - without unlocked session, just ordinary get/set.
It needed to mode safely (and friendly!) store and retrieve passphrases then from env or shell.
Checklist:

Add KeyChain support

---

.github/workflows/ci.yml

Ubuntu 20.04 LTS runner has been removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
Checklist:

chore: Fix docs CI job

---

Cargo.lock
cargo-crev/CHANGELOG.md
cargo-crev/src/main.rs
cargo-crev/src/opts.rs

Also make filer for version indepent of if name filter was applied as these are independent on the cli.
Checklist:

Implement finding proof by git revision
